# Generated by Django 5.2.7 on 2025-10-23 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_alter_post_options_alter_post_meta_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نوشته شدن')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_verify', models.BooleanField(default=False, verbose_name='مورد تائید')),
                ('is_pin', models.BooleanField(default=False, verbose_name='پین')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comment', verbose_name='پاسخ به')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='برای پست')),
            ],
        ),
    ]
