# Generated by Django 5.2.7 on 2025-10-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_check_of_author_post',
            field=models.BooleanField(default=False, verbose_name='چک شده توسط نویسنده'),
        ),
    ]
