# Generated by Django 5.2.7 on 2025-11-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_is_check_of_author_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
