# Generated by Django 5.2.7 on 2025-10-16 06:18

import apps.blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='موضوع')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.blog.models.thumbnail_upload_path, verbose_name='تصویر شاخص')),
                ('description', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('write_date', models.DateTimeField(auto_now_add=True, verbose_name='نوشته شده در تاریخ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='اخرین به روز رسانی')),
                ('is_active', models.BooleanField(verbose_name='فعال بودن')),
                ('is_pin', models.BooleanField(verbose_name='پین بودن')),
                ('is_verify', models.BooleanField(verbose_name='تایید شده')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
