# Generated by Django 5.2.7 on 2025-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-write_date', 'update_date', 'title', 'is_pin', 'is_active', 'is_verify'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_at',
            new_name='update_date',
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, null=True, verbose_name='توضیح سئو'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='بین کلمات باید , بگذارید', null=True, verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_name',
            field=models.CharField(blank=True, null=True, verbose_name='نام سئو'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, max_length=110, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
