# Generated by Django 5.2.7 on 2025-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_update_at_post_update_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['is_pin', '-write_date', 'update_date', 'title', 'is_active', 'is_verify'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='بین کلمات باید (,) بگذارید', null=True, verbose_name='کلمات کلیدی'),
        ),
    ]
