# Generated by Django 5.2.7 on 2025-11-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_course_post_post_mainpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'درس ها'},
        ),
    ]
