# Generated by Django 5.2.7 on 2025-11-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_course_options'),
        ('users', '0007_minimainpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_mainpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mainpoint', verbose_name='درس مربوطه'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
