# Generated by Django 5.2.7 on 2025-10-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='users.roles', verbose_name='نقش کاربر'),
        ),
    ]
