# Generated by Django 5.2.7 on 2025-10-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_role_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_comments',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد نظرات با تائید شما ارسال می شوند', verbose_name='تائیدی بودن نظرات'),
        ),
    ]
